### ISSUE TITLE
ParseError in merge.ticketing.tickets.remoteFieldClassesList

### ISSUE THREAD

**Issue by MateusZitelli** [merge-api/merge-node-client#16]
The method fails due to a ParseError for a Jira account with this stack trace:

```
ParseError: response -> results -> [3] -> item_schema -> item_choices -> [0]: Expected string. Received object.; response -> results -> [6] -> item_schema -> item_choices -> [0]: Expected string. Received object.; response -> results -> [8] -> item_schema -> item_choices -> [0]: Expected string. Received object.; response -> results -> [10] -> item_schema -> item_choices -> [0]: Expected string. Received object.; response -> results -> [12] -> item_schema -> item_choices -> [0]: Expected string. Received object.; response -> results -> [13] -> item_schema -> item_choices -> [0]: Expected string. Received object.; response -> results -> [16] -> item_schema -> item_choices -> [0]: Expected string. Received object.; response -> results -> [17] -> item_schema -> item_choices -> [0]: Expected string. Received object.
    at node_modules/@mergeapi/merge-node-client/core/schemas/builders/schema-utils/getSchemaUtils.js:25:19
    at Generator.next (<anonymous>)
    at fulfilled (node_modules/@mergeapi/merge-node-client/core/schemas/builders/schema-utils/getSchemaUtils.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errors: [
    { path: [Array], message: 'Expected string. Received object.' },
    { path: [Array], message: 'Expected string. Received object.' },
    { path: [Array], message: 'Expected string. Received object.' },
    { path: [Array], message: 'Expected string. Received object.' },
    { path: [Array], message: 'Expected string. Received object.' },
    { path: [Array], message: 'Expected string. Received object.' },
    { path: [Array], message: 'Expected string. Received object.' },
    { path: [Array], message: 'Expected string. Received object.' }
  ]
}
```

**Comment by dsinghvi** [comment]
👀 thanks for the bug report @MateusZitelli. @rmkonnur looks like this might be an issue in the OpenAPI spec not leveraging `oneOf`?

**Comment by dsinghvi** [comment]
@MateusZitelli this should be fixed in the latest SDK, closing this issue! Feel free to reopen if not the case.
